import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Router from "next/router";
import Container from 'react-bootstrap/Container';
import Navbar from 'react-bootstrap/Navbar';
import Nav from 'react-bootstrap/Nav';
import NavDropdown from 'react-bootstrap/NavDropdown'
import Button from 'react-bootstrap/Button';


export default function Home() {
  return (
    <>
      <Head>
        <title>HACK WASHU 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


  <Container>
    <p>text</p>


  </Container>
  </>
  )
}
