import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Router from "next/router";
import Container from 'react-bootstrap/Container';
import Navbar from 'react-bootstrap/Navbar';
import Nav from 'react-bootstrap/Nav';
import NavDropdown from 'react-bootstrap/NavDropdown'
import Button from 'react-bootstrap/Button';


export default function Home() {
  return (
    <>
      <Head>
        <title>HACK WASHU 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <Navbar bg="dark" variant="dark">
        <Container>
          <Navbar.Brand href="#home">
            <img
              alt=""
              src="/hackwashulogo.png"
              width="30"
              height="30"
              className="d-inline-block align-top"
            />{' '}
            HACK WASHU 2022
          </Navbar.Brand>
        </Container>
      </Navbar>

  <Container>
    <p>text</p>


  </Container>
  </>
  )
}
